# Generated by Django 5.1.2 on 2024-11-24 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_event_event_type'),
        ('core', '0003_alter_user_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.user'),
        ),
    ]
